### ISSUE TITLE
App Navigation become too complex for less tech savvy people.

### ISSUE THREAD

**Issue by AiOTnext** [Path-Check/covid-safe-paths#391]
Check overlap functionality is no longer there but it should be replaced with alternate approach .

Clicking on a particular button and checking that you are safe gives psychological assurance to the user. 
And avoid being misleading by false positive status by faulty configuration.

And Mapview is not working as screenshot provided on covid safepath website for v2.

**Comment by E3V3A** [comment]
> Check overlap functionality is no longer there but it should be replaced with alternate approach .

Why was it removed in the first place?  :-1:

**Comment by kenpugsley** [comment]
Was removed for v1 partly to reduce scope to get a quality v1 product complete, and partly due to licensing and privacy issues with google maps.  There are other mapping options of course, and we're not saying the map functionality won't return, but for now it was the decision we needed to make.

There are designs in progress for v2 (and v3).  My suggestion would be to work with the product management teams on that request.

**Comment by Patrick-Erichsen** [comment]
Closing as the UI navigation has been refactored since the time of this issue.
