### ISSUE TITLE
BUG: Zero policing of what can be entered as a URL for a Health Authority - DHM-S1-18

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#456]
There is apparently no policing of what text can be entered as a URL.  I was able to paste 1000s of lines of text here.
o   I haven’t explored this, but if there is no policing here, I’d expect it may be possible to attack the app here using SQL injections, very long text etc.

For security reasons, it would seem prudent to put some limits on what can be entered here.

**Comment by denispapakul** [comment]
I can fix it, actually, I need to know max length or URL, which can be entered for a Health Authority. Please, assign me to this ticket.

**Comment by diarmidmackenzie** [comment]
The correct answer for "what is the maximum length of a URL" is complicated:

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

Key limits are:
- IE/Edge won't allow more than 2000 chars in the address bar.  But most other browsers will. (I can envisage wanting to put a URL in a browser for troubleshooting reasons).
- While RFCs don't set any actual limit, they advise that systems SHOULD support up to 8000 chars.

I think 2000 chars is probably enough.  But there is a risk I'm wrong, and that there is a reason why a URL might need to be longer than that.

For me the most important thing is to have some limit (so that we don't risk a buffer overrun bug).  

So I suggest we take the more conservative position of 8000 chars.

**Comment by diarmidmackenzie** [comment]
I've been thinking about testing, and formed the view that if a tester (manual or automated) wants to test a scenario where the "Healthcare Authority" provides some specific, known, set of data points, a neat way to achieve that would be to encode the full required JSON data set in the configured URL, and have a web server that simply takes that request & serves it back up to the app.

Given this use case, having plenty of room in the URL would be quite useful.  I think 8000 chars is still plenty, but a good reason to go for 8000 rather than 2000.

**Comment by E3V3A** [comment]
iOS and Android browser apps are all different and continuously updated, so there is not much point to comparing it to what your Windows Desktop browsers can handle.

Good practice would be to hard limit the URL length to something sensible, to ensure any browser can handle it. Speaking of, I think the URL is used in a POST request later, independent of browser, is it not? Or are you also talking about the links to documents and authority website info?

**Comment by diarmidmackenzie** [comment]
This is about the limit for a Health Authority URL.  Currently there is no limit, which is an exposure.

I am proposing 8000 chars.

Do you propose a different value?  If so, what value & why?

**Comment by Mr-EZG** [comment]
Currently, I am going to attempt to create a working version where the url would fall into the 8000 char limit and reference a general open-source regex pattern for the url before trying to send it.

Source of regex pattern (Non Http protocol): https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url 
Currently, I am trying to use the non-http protocol out of giving more freedom for the url in case the web-site doesn't follow the http protocol (and be more loose for world-use)

Note: the current approach runs locally and would just check that the attempted url would point to a valid format of a url rather than testing if it points to a live url which might be more desirable in future releases. The 8000 char limit was chosen based off of the conversation above but should be a moderately easy change once implemented. This process was considered to help limit potential attacks.

Are there any thoughts on improvement with this approach? Would the pattern checking be redundant if we have the character limit? or is it still not enough? These are things that I am not too sure of, but hope to find out.
