### ISSUE TITLE
CONCERN: Unnecessary variation of terminology - DHM-S1-26

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#469]
o   “Select Healthcare Authorities” vs “Choose Healthcare Authorities”
o   “Healthcare Authorities” vs. “Trusted Sources” vs. “trusted healthcare authorities”

As well as helping to avoid user confusion, having single, consistent terms will also help with Internationalization.

**Comment by tremblerz** [comment]
Which screens are we talking about here, can you give more info?

**Comment by E3V3A** [comment]
Many developers many interpretations. The only problem I have, by just doing a search and replace, is that the word "Trusted" should be left out. There are currently no trusted healthcare authorities in the world right now. Everybody are more or less equally clueless with huge issues providing reliable data.

**Comment by diarmidmackenzie** [comment]
Hmm - now I can't find "Select Healthcare Authorities" anywhere.  That may have been seen at an earlier version.  Apologies.

There is a page called "Choose health authority", which includes all of:

"Choose health authority"
"Trusted Sources"
"trusted healthcare authorities"
"Add Trusted Source"

So I thin k we need to decide:
- Are they health authorities or healthcare authorities?
- What is our policy on capitalization?  I don;'t care whether we capitalize every word in a heading or not.  But we shoudl be consistent.
- Should we get rid of "trusted" as an adjective for healthcare authorities?  I think we definitely should remove it.
- Do we need to keep the term "Trusted Sources" or should we just replace with "Health authorities"?  I think we should replace.

**Comment by E3V3A** [comment]
"health" and "healthcare" is not the same. 
I suggest to just make PR and replacing everything above with `healthcare authority`.

**Comment by diarmidmackenzie** [comment]
Slight worry that "healthcare authority" may overrun the available space on some screens.

**Comment by kenpugsley** [comment]
As the wording in the app has been approved now considered final, this discussion should happen via the product management group.  Not saying that we shouldn't change the language, but we do need to work in coordination.  Please contact @xian on slack on this issue.

Also mentioning @penrods so this comes up in his feed.

**Comment by mediajunkie** [comment]
Will review and follow up today

**Comment by mediajunkie** [comment]
re this one does Alina have a UX writer on her team? The product should have a style guide with rules to cover things like this:

> What is our policy on capitalization? I don;'t care whether we capitalize every word in a heading or not. But we should be consistent.

**Comment by mediajunkie** [comment]
Discussed with Kristen from comms and of course this is not an MVP blocker just yet but here is where we got to:

- use "health authority" and not "healthcare authority"
- trusted is ok because presumably things are not added to the global registry without some sort of vetting (is that a legit assumption), and it might be worth providing a way for the user to "find out more" about why these sources are trustworthy
- the Trusted Sources heading is a bit odd as it doesn't add much to the screen name (Choose health authority) and functions mainly as a label for the items on the pick list, but I don't have a better idea for what to put there besides maybe no need for a header there, except that may violate a design pattern in the app
- rules like when to use sentence case vs title case in the app are a matter of design, part of a copy stylesheet that ought to be maintained by a content strategist or UX writer and kept in sync with comms style guidelines -- not sure if Alina has anyone on her team owning that right now. If it's something we want product to take I'm sure we can do that too.

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
