### ISSUE TITLE
CONCERN: Documentation of language support - DHM-S1-32

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#474]
We need some documentation telling us the expected status of support for various languages, so we know what to expect when we test.

I have seen many comments / commits about various languages, but no consolidated overall status.

When switching my phone to Italian, I note the app stays in English.  Is that a bug?  Or do we simply not have Italian language support yet?

I'd like a doc, so that I can know, and raise issues where appropriate.

Probably this shoudl be in the MVP documentation, or successors of that?
https://docs.google.com/document/d/13R-oHWuuodsBBtPH974crMuow0H2UihW6DY5CfkHGgE/edit#heading=h.v6prkwjuyv0f

Can't find any mention (searched for "language" and "translation").

**Comment by tremblerz** [comment]
@alpita-masurkar can weigh in on this I guess

**Comment by alpita-masurkar** [comment]
Hi @diarmidmackenzie, as Ken mentioned in another issue, there were several translations before that were removed or not merged because the content in the app got changed.
The number 16 that you are referring to is based on this old version and doesn't accurately capture the current status.
If you would like me to update some documentation on the current status of the languages, I'd be happy to add them somewhere.
In the meanwhile, this is the document that I currently use to track our language support: https://docs.google.com/spreadsheets/d/1Vm6RzpgQQ1PvF6ZShHeK9NkBbEHCz0gFCRHe5GYPtUg/edit#gid=1901130528

Do have a look at it and let me know if you'd like something else to ease this process. (Sheet 2 is the sheet for the newer Safe Paths content and the status of various languages)

Thank you.

**Comment by diarmidmackenzie** [comment]
That info looks good - we just need to work on discoverability of it.  I'll try to do something here in terms of a set of useful links for testers.

**Comment by alpita-masurkar** [comment]
Perfect! Let me know how I can help or if you want to move this document somewhere.
Once there's a resolution on how to move forward with this, we can close this issue.

**Comment by Patrick-Erichsen** [comment]
Closing this as we are now using Lokalise.
