### ISSUE TITLE
Latest news : Appears in english, even when language is selected as italian

### ISSUE THREAD

**Issue by vedhakannan** [Path-Check/covid-safe-paths#633]
Issue :  The whole latest news section appears in english.

## Version : 0.9.5

- Type of phone: Android
- OS Version: 10
- Model: Samsung Galaxy Note 10+ 

## Actual behaviour

In   "latest news" - "ultime novità" section: The whole section  about the new is in English. Suggested translations below:
 The header   "No updates" --> Nessuna notizia.

 "There are no news items   at this time, please check back later" --> Al momento non ci sono   nuove notizie, perfavore controlla più tardi. 

"Learn more about COVID   SafePaths" --> Scopri di più su COVID SafePaths. 

"FAQ"   --> FAQ. "Join us" --> Unisciti a noi. 

"Signup for   updates" --> Registrati per ricevere aggiornamenti ( or -->   Registrati per restare aggiornato).

 "Contact us" --> Contattaci.   "Related research" --> Ricerche correlate.

 "Private   Kit" --> Kit privato (or --> Kit personale) it depends from what  does that link for. "About" - Su di noi.

## Expected Behavior 
All of them to be translated to italian

Screenshots : 
https://www.jotform.com/uploads/AppQuality/201096241235345/4632140126817427183/20200420_172743.jpg

https://www.jotform.com/uploads/AppQuality/201096241235345/4632140126817427183/20200420_172847.jpg

**Comment by matteocrippa** [comment]
Can you format the request according to the template provided and check first if the issue was not raised already + test against the latest version of the app?

**Comment by summetj** [comment]
The latest  release is 0.9.5 which can be found here: https://github.com/tripleblindmarket/covid-safe-paths/releases  (only a few days out of date)

Otherwise, to get closer to development branch you would have to follow the directions at https://github.com/tripleblindmarket/covid-safe-paths/blob/develop/README.md to set up a full developer environment.

**Comment by matteocrippa** [comment]
@summetj doubt was more that the information above are coming from the one that is in the store, because some are not replicate as far as I see.

@vedhakannan the content you are referring to are coming from an external web page that is not localizable from within the app.

Also it applies, for the reason above, to all the language and this will need extra rework somewhere else.

@alpita-masurkar is there any way to localize that content passing a querystring param in the url asking for a specific language?

**Comment by summetj** [comment]
@alpita-masurkar  - Should we close this issue?
