### ISSUE TITLE
SP location is inaccurate in one instance by 346m

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/covid-safe-paths#691]
## Version

- Type of phone: Android
- OS Version: 9
- Model: Samsung Galaxy S8

The location history recorded by Safe Places is inaccurate on one data point by 346 metres.  The user has also exported their google location history from the same device and provided to me.  The google location history shows the correct location with a high confidence factor.

Additional information can be provided privately/on slack.

**Comment by diarmidmackenzie** [comment]
I have also been investigating GPS data accuracy recoirded by Safe Paths & have similar concerns that our data is
(a) not accurate enough for Safe Paths needs
(b) not as accurate as other GPS services.

This is across 3 phone models (Motorola G7, Samsung J6 and Redmi 6A.

One hypothesis is detailed here:
https://pathcheck.atlassian.net/wiki/spaces/TEST/pages/24412603/26+April+-+GPS+comparison+testing+with+Google+Maps

I wonder whether we are taking the first info we get back on the GPS API as correct, but in reality we need to do more to let the GPS signal "train" before taking it as meaningful?

If we do already have some logic in the app to accommodate GPS training times (or if we don't and we don't know what logic to implement), I wonder whether we could reach out to assistance to organizations who have solved this problem before for some guidance, e.g. Google Maps, Pokemon Go, Geocaching, Strava etc.?

**Comment by sergesemashko** [comment]
Just wanted to share, I've noticed in some GPS hardware (other than smartphones) that quality of GPS signal matters a lot for accurate location. If there is a way to identify signal strength on a smartphone we could add different handling.

**Comment by diarmidmackenzie** [comment]
We are also testing with various GPS Loggers in the Play Store.  Using exactly the same hardware they are delivering much better data than our app.  So this is a software issue.

What they do to get the better data, I don't know - maybe they factor in signal strength.  At least one of them is Open Source, so we can have a look.

**Comment by troach-sf** [comment]
I wanted to share a few quick findings. There should be no need to pull in a brand new library. The existing one seems sufficient with a few modifications. For Android, the library is configured to use ACCURACY_FINE location, but that alone doesn’t ensure getting an accurate coordinate. The background geolocation library pulls in an android/ios wrapper to do a lot of its internal work. Here is the line where android requests an update: https://github.com/mauron85/background-geolocation-android/blob/58464febf6901f1e489817e4425418d48443929b/src/main/java/com/marianhello/bgloc/LocationManager.java#L98 Rather than pulling a single location, we should probably pull multiple locations, until the accuracy level reports < X (need to determine threshold here) meters. Accuracy is a field that is already available on the location model that comes back.

**Comment by Patrick-Erichsen** [comment]
Closing as we have ongoing work in-flight to improve both the reliability and accuracy of our location tracking.
