### ISSUE TITLE
iOS "Finish Setup" button causes temporary UI lock

### ISSUE THREAD

**Issue by troach-sf** [Path-Check/covid-safe-paths#727]
## Version

- Type of phone: iPhone
- OS Version: 13

## Steps to reproduce

I'm seeing a 3-5 second thread UI thread lock clicking "Finish Setup" on the last onboarding screen.

## Expected Behavior

Clicking "Finish Setup" doesn't lock screen. If we have any long running processes that need to complete before leaving this screen, they should be queued up asynchronously.

**Comment by matteocrippa** [comment]
@troach-sf are you testing a release or debug version installed by yourself?

**Comment by troach-sf** [comment]
develop branch, debug/release builds on real iOS devices. I suspect the lock is actually on the home screen, not the last onboarding screen. I've seen the lock occur on the home screen as well. My guess is that it consistently locks after clicking "Finish Setup" because its attempting to display the home screen being initialized, and it locks up before it is able to draw any frames of that screen.

**Comment by matteocrippa** [comment]
If the app has been built using Xcode and Xcode has debugger on, the issue should be the UI Thread check.

You can try checking if this happens also without any usb attach to device or in that scenario it works fine.

**Comment by troach-sf** [comment]
The issue is the call to PushNotification.configure: https://github.com/tripleblindmarket/covid-safe-paths/blob/develop/app/services/LocationService.js#L220. When removed, the lock no longer occurs. 

I've got a few tickets I need to close out in the next few days before I could get to looking further into this. Maybe someone else can in the meantime.

**Comment by summetj** [comment]
@troach-sf - Should this qualify for the iOS tag, or does the lag/lock occur on Android as well?

**Comment by sparks2209** [comment]
Please assign this to me

**Comment by sparks2209** [comment]
This issue is not happening in latest PathCheck GPS target.
Sharing few of the observations while profiling app.

App is consuming 67MB before launching.
<img width="1680" alt="Screenshot 2020-05-28 at 11 49 16 AM" src="https://user-images.githubusercontent.com/46887319/83108243-1d6b2880-a0dd-11ea-8bc0-c16ad0d306b8.png">

Other parts of app which consuming memory as below.
<img width="1680" alt="Screenshot 2020-05-28 at 12 04 01 PM" src="https://user-images.githubusercontent.com/46887319/83108331-4095d800-a0dd-11ea-95c9-3089f96ad219.png">
<img width="1680" alt="Screenshot 2020-05-28 at 12 11 32 PM" src="https://user-images.githubusercontent.com/46887319/83108341-468bb900-a0dd-11ea-8135-60d220031d59.png">

I could image decoding is happening from main thread
<img width="1680" alt="Screenshot 2020-05-27 at 4 49 13 PM" src="https://user-images.githubusercontent.com/46887319/83108407-5c997980-a0dd-11ea-84d5-161c73e51811.png">

**Comment by troach-sf** [comment]
As noted above, the lockup issue was specific to being called with PushNotification.configure() on the home screen. That call may have been removed, which would have fixed the issue.

**Comment by summetj** [comment]
Ok, I'm going to close out this issue, thanks @sparks2209 for confirming it is no longer an issue.
