### ISSUE TITLE
Battery Usage is high

### ISSUE THREAD

**Issue by vitorpamplona** [Path-Check/covid-safe-paths#91]
Not unexpected but I think we can do better. 

![Screenshot_20200318-192536](https://user-images.githubusercontent.com/532031/77017082-d24fcf00-694f-11ea-8391-c454adbba980.png)

**Comment by E3V3A** [comment]
I have no idea how you can say this is high. Looks just fine. 

It's funny that no matter what app you design, using GPS, someone complains that battery usage is high. Well, you know what? **Having GPS enabled, is using the battery continuously.** There is no way to get around this. Please close this issue.

**Comment by vitorpamplona** [comment]
There are so many ways we can decrease battery usage... GPS interval is one of them. 
Like I wrote in the original description: "I think we can do better".

**Comment by E3V3A** [comment]
Any progress on this? 

When we wrote our mobile anti-tracking software we were using the inertial sensors to activate the GPS, to ensure the GPS was only used when on the move. Thus most of the time it will be off for someone not "running" around. That in combination with a radius of which nothing need to be done or updated.

**Comment by penrods** [comment]
My understanding from feedback in the field is that battery usage is acceptable.  If someone can quantify and wants to test, please do so.

Until then, this is very low priority in my book.

Also, the react component used for Geo info is supposed to use accelerometers, etc up minimize calls to more power expensive GPS subsystems.  So I think we are doing decently.

**Comment by denispapakul** [comment]
I think we can check the location and, for example, if the user is at home or for a long time in some other place - turn off geolocation tracking. But geolocation accuracy may suffer from such a feature, because you need to know when to turn on geolocation tracking again.

**Comment by acooley** [comment]
I can fix this.  I have a similar project I started working on before discovering this one.  It uses BLE for contact tracing which is far better at determining if two phones have not been socially distancing.  The way that I've implemented it all the handsets wake up at exactly the same time and look for each other, then BLE goes off.  I've also put a ton of work into making sure that the implementation works efficiently, works on startup, etc.  With my implementation there is almost 0 impact on battery performance.  I build it this way after I decompiled the TraceTogether application and decided that I didn't like it because I knew it would be a batter hog.

Please let me help.  I have lost a lot of sleep to get the bluetooth implementation I have working correctly and the rest of the app is still not complete, but that part works really well and I can replicate it on iOS easily as BLE on that platform is way less of a pain in the ass.

**Comment by tstirrat** [comment]
We're looking into GPS accuracy and efficiency, including battery usage: https://pathcheck.atlassian.net/browse/SAF-175
